extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

env:
  node: true

rules:
  "no-async-promise-executor":
    - off

  "@typescript-eslint/no-explicit-any":
    - off

  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: none

  require-yield: 0

parserOptions:
  project: "./tsconfig.json"

ignorePatterns:
  - jest.config.js
  - "dist/"
  - "examples/"
