extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

env:
  node: true

rules:
  "import/order":
    - error
    - alphabetize: { order: "asc" }

  "@typescript-eslint/no-explicit-any":
    - off

  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: none

  require-yield: off

parserOptions:
  project: "./tsconfig.json"

ignorePatterns:
  - "/*.ts" # ignore root level .ts files
  - "/*.js" # ignore root level .js files
  - dist/
  - docs/
  - examples/
  - coverage/
